### PR TITLE
[MOB-1947] iOS: opt out feature

### PR DESCRIPTION
**Pull request by th-anguyen**
Be sure to update the react-native-one dependency in example/package.json to use `1.5.0-alpha.7` for testing. Also, add ONE credentials to example/config/one.js

I got rid of the different log levels api call i.e. `One.setLogLevel(One.LogLevelAll)` and simplified it to just enable/disable all logs
i.e. 
`One.enableLogs(true)`

my local react-native versions
`react-native-cli: 2.0.1`
`react-native: 0.63.4`

### CODE REVIEW

**Review by th-jtullgren — COMMENTED** [review]
Where are the doc updates calling out the details of opt out?

**Comment by th-anguyen** [comment]
> 

The docs were already added in the Android opt out PR: https://github.com/thunderheadone/one-sdk-react-native/blob/develop/README.md#opt-an-end-user-out-of-tracking

**Comment by th-jtullgren** [comment]
> > Where are the doc updates calling out the details of opt out?
> 
> The docs were already added in the Android opt out PR: https://github.com/thunderheadone/one-sdk-react-native/blob/develop/README.md#opt-an-end-user-out-of-tracking

There is nothing in the docs about opt out keychain which is ios specific, hence my question.

**Comment by th-anguyen** [comment]
> > > Where are the doc updates calling out the details of opt out?
> > 
> > 
> > The docs were already added in the Android opt out PR: https://github.com/thunderheadone/one-sdk-react-native/blob/develop/README.md#opt-an-end-user-out-of-tracking
> 
> There is nothing in the docs about opt out keychain which is ios specific, hence my question.

Oh that's right, thanks for the reminder on that part.  It's added now.

**Comment by th-jtullgren** [comment]
Please explain what happens if the ios only method is called in android.  Does it no op or crash for example.

**Comment by th-anguyen** [comment]
> Please explain what happens if the ios only method is called in android. Does it no op or crash for example.

This causes an error.  I have added a dummy method in Android plugin to resolve this.

**Review by th-jtullgren — APPROVED** [review]

**Review by th-skhozin — APPROVED** [review]

**Pull request merged**
